name: lichamduong
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Common
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  cached_network_image: ^2.3.3
  flutter_icons: ^1.1.0
  toast: ^0.1.5
  get: ^3.16.1
  flame: ^0.28.0
  http: ^0.12.2
  rxdart: ^0.24.1
  launch_review: ^2.0.0
  sqflite: ^1.3.2+1
  path_provider: ^1.6.24
  imagebutton: ^0.0.6
  audioplayers: ^0.15.1
  get_it: ^4.0.4
  awesome_dialog: ^1.2.1

  #  Network
  dio:
  connectivity: ^2.0.1

  #  BloC
  #  equatable: ^1.2.4
  #  flutter_bloc: ^6.0.5

  #  Sqlite - Local prefrences
  #  moor: ^3.3.1
  shared_preferences: ^0.5.10
  rx_shared_preferences: ^1.3.3

  #Other

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/langs/
    - assets/images/
    - assets/audio/

#  fonts:
#    - family: Shrikhand
#      fonts:
#        - asset: assets/fonts/Shrikhand-Regular.ttf
#    - family: Montserrat
#      fonts:
#        - asset: assets/fonts/Montserrat-MediumItalic.ttf
#          weight: 400
#        - asset: assets/fonts/Montserrat-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/Montserrat-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Montserrat-SemiBold.ttf
#          weight: 600
